# é¡¹ç®contextPath çªåç¬è®° https://blog.52itstyle.vip
server.servlet.context-path=/
# æå¡ç«¯å£
server.port=8081
# sessionæå¤§è¶æ¶æ¶é´(åé)ï¼é»è®¤ä¸º30
server.session-timeout=60
# tomcatæå¤§çº¿ç¨æ°ï¼é»è®¤ä¸º200
server.tomcat.max-threads=100
# tomcatçURIç¼ç 
server.tomcat.uri-encoding=UTF-8

server.servlet.session.tracking-modes = cookie
server.servlet.session.cookie.http-only =true

spring.servlet.multipart.enabled =true
spring.servlet.multipart.max-request-size=20MB
spring.servlet.multipart.max-file-size=20MB

# éææä»¶è¯·æ±å¹éæ¹å¼
spring.mvc.static-path-pattern=/**

#spring.thymeleaf.mode=LEGACYHTML5

#spring boot 2.x  åæ°åå
spring.aop.proxy-target-class=true
spring.thymeleaf.mode=HTML
#dev app
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false
spring.thymeleaf.cache-period=0
spring.thymeleaf.template.cache=false

#æ³¨æä¸­æä¹±ç 
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/smartparking?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Specify the DBMS
spring.jpa.database = MYSQL
# Show or not log for each sql query
spring.jpa.show-sql = false
spring.jpa.open-in-view = false
# DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
spring.jpa.hibernate.ddl-auto = update
# Hibernate 4 naming strategy fully qualified name. Not supported with Hibernate 5.
#spring.jpa.hibernate.naming.strategy = org.hibernate.cfg.ImprovedNamingStrategy
# stripped before adding them to the entity manager)
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Dialect
# æ°ç¹æ§
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.max-lifetime =30000
spring.datasource.hikari.connection-test-query=SELECT 1

# æä»¶æ å°è·¯å¾ Linux éè¦æ¹æå¶å¯¹åºçè·¯å¾
file.path = D:/images
# é¡¹ç®è®¿é®å°å çäº§ç¯å¢è¯·èªè¡æ¿æ¢
project.url = https://paycloud.vip

# ===================================
# ç¾åº¦äººå·¥æºè½
# ===================================
bai-du.appId = 99044931
bai-du.apiKey = Iwjz9lM1SCdv6lcKxnJQLgua
bai-du.accessKeySecret = 4mwlnDI0ozb4cBv4q3cfoABM9qJFDBgn